// first attempt at using JSON

const websites = [
    { "title": "On ‘Saturday Night Live,’ a Milestone for Domingo", "url": "https://www.nytimes.com/2025/10/19/arts/television/snl-sabrina-carpenter-trump-george-santos.html", "description": "Marcello Hernández’s viral character kicked off an episode hosted by Sabrina Carpenter, while President Trump visited a most unlikely podcast.", "sourceType": "online journal", "date": "2024-10-20" },

    { "title": "Major Sites Hobbled by Amazon Web Services Outage", "url": "https://www.wsj.com/tech/amazon-web-services-internet-outage-728806dc?mod=hp_lead_pos1", "description": "Outage disrupts services from retailers to airlines, social-media apps, financial-services companies and more", "sourceType": "online journal", "date": "2024-10-20" },

    { "title": "Historic jewels stolen in ‘national disaster’ for France: What we know about missing Louvre treasures", "url": "https://www.cnn.com/2025/10/20/style/louvre-heist-which-jewels-stolen-intl-hnk", "description": "See what was stolen from the Louvre in brazen seven-minute heist that left France reeling", "sourceType": "online journal", "date": "2024-10-19" },

    { "title": "9th Circuit court rules on Trump's National Guard deployment in Portland", "url": "https://www.foxnews.com/politics/9th-circuit-court-rules-trumps-national-guard-deployment-portland", "description": "A three-judge panel, comprised of two Trump appointees and one Clinton appointee, heard the case last week", "sourceType": "online journal", "date": "2024-10-20" },

    {
        "title": "Diet Pepsi(Live from 2025 Las Culturistas Culture Awards)", "url": "https://www.youtube.com/watch?v=hN0CedumyBo", "description": "Provided to YouTube by Universal Music Group Diet Pepsi (Live from 2025 Las Culturistas Culture Awards) · Ben Platt Diet Pepsi ℗ 2025 Interscope Records Released on: 2025-08-10 Mastering Engineer, Engineer, Mixing Engineer, Producer: Gabe Lopez Producer: Leland Composer Lyricist: Elvira Anderfjärd Composer Lyricist: Luka Kloser Composer Lyricist: Addison Rae Auto-generated by YouTube.", "sourceType": "digital source", "date": "2024-08-09"
    },

    { "title": "The State of the AI Industry is Freaking Me Out", "url": "https://www.youtube.com/watch?v=Q0TpWitfxPk", "description": "Go to https://ground.news/hank for a better way to stay informed. Subscribe for 40% off unlimited access to world-wide coverage through my link. Edited by Digital Gator:    / @digitalgator  ", "sourceType": "digital source", "date": "2024-10-16" },

    { "title": "Wikipedia: Cardi B", "url": "https://en.wikipedia.org/wiki/Cardi_B", "description": "Cardi B is the female rapper with the most number-one singles (five) on the Billboard Hot 100, the only female rapper to achieve multiple solo number-ones, and the only to earn number-one singles in two decades (2010s and 2020s)", "sourceType": "online journal", "date": "2024-10-20" },

    {
        "title": "University of Colorado Boulder", "url": "https://www.usnews.com/best-colleges/university-of-colorado-boulder-1370", "description": "University of Colorado Boulder is a public institution that was founded in 1876. In the 2026 edition of Best Colleges, University of Colorado Boulder is ranked No. #97 in National Universities. It's also ranked No. #46 in Top Public Schools.", "sourceType": "online journal", "date": "2024-10-20"
    }
]


const searchBar = document.getElementById('main-search-bar');

searchBar.addEventListener('keydown', (event) => {
    if (event.key === 'Enter') {
        // To prevent form from submitting
        // search logic...
        let currentKeyword = "null";
        currentKeyword = searchBar.value.trim();
        if (currentKeyword != "null" || ' ') {
            console.log(currentKeyword);

        }
    }
});