// first attempt at using JSON
// Referenced https://www.w3schools.com/js/js_json_syntax.asp

const WEBSITES = [
    {
        "title": "On ‘Saturday Night Live,’ a Milestone for Domingo",
        "url": "https://www.nytimes.com/2025/10/19/arts/television/snl-sabrina-carpenter-trump-george-santos.html",
        "description": "Marcello Hernández’s viral character kicked off an episode hosted by Sabrina Carpenter, while President Trump visited a most unlikely podcast.",
        "sourceType": "online journal",
        "date": "2024-10-20"
    },

    {
        "title": "Major Sites Hobbled by Amazon Web Services Outage", "url": "https://www.wsj.com/tech/amazon-web-services-internet-outage-728806dc?mod=hp_lead_pos1",
        "description": "Outage disrupts services from retailers to airlines, social-media apps, financial-services companies and more",
        "sourceType": "online journal",
        "date": "2024-10-20"
    },

    {
        "title": "Historic jewels stolen in ‘national disaster’ for France: What we know about missing Louvre treasures",
        "url": "https://www.cnn.com/2025/10/20/style/louvre-heist-which-jewels-stolen-intl-hnk",

        "description": "See what was stolen from the Louvre in brazen seven-minute heist that left France reeling",
        "sourceType": "online journal",
        "date": "2024-10-19"
    },

    {
        "title": "9th Circuit court rules on Trump's National Guard deployment in Portland",
        "url": "https://www.foxnews.com/politics/9th-circuit-court-rules-trumps-national-guard-deployment-portland",
        "description": "A three-judge panel, comprised of two Trump appointees and one Clinton appointee, heard the case last week",
        "sourceType": "online journal",
        "date": "2024-10-20"
    },

    {
        "title": "Diet Pepsi(Live from 2025 Las Culturistas Culture Awards)",
        "url": "https://www.youtube.com/watch?v=hN0CedumyBo",
        "description": "Provided to YouTube by Universal Music Group Diet Pepsi (Live from 2025 Las Culturistas Culture Awards) · Ben Platt Diet Pepsi ℗ 2025 Interscope Records Released on: 2025-08-10 Mastering Engineer, Engineer, Mixing Engineer, Producer: Gabe Lopez Producer: Leland Composer Lyricist: Elvira Anderfjärd Composer Lyricist: Luka Kloser Composer Lyricist: Addison Rae Auto-generated by YouTube.",
        "sourceType": "online video",
        "date": "2024-08-09"
    },

    {
        "title": "The State of the AI Industry is Freaking Me Out",
        "url": "https://www.youtube.com/watch?v=Q0TpWitfxPk",
        "description": "Go to https://ground.news/hank for a better way to stay informed. Subscribe for 40% off unlimited access to world-wide coverage through my link. Edited by Digital Gator:    / @digitalgator  ",
        "sourceType": "online video",
        "date": "2024-10-16"
    },

    {
        "title": "Wikipedia: Cardi B",
        "url": "https://en.wikipedia.org/wiki/Cardi_B",
        "description": "Cardi B is the female rapper with the most number-one singles (five) on the Billboard Hot 100, the only female rapper to achieve multiple solo number-ones, and the only to earn number-one singles in two decades (2010s and 2020s)",
        "sourceType": "wiki",
        "date": "2024-10-20"
    },

    {
        "title": "University of Colorado Boulder",
        "url": "https://www.usnews.com/best-colleges/university-of-colorado-boulder-1370",
        "description": "University of Colorado Boulder is a public institution that was founded in 1876. In the 2026 edition of Best Colleges, University of Colorado Boulder is ranked No. #97 in National Universities. It's also ranked No. #46 in Top Public Schools.",
        "sourceType": "online journal",
        "date": "2024-10-20"
    },

    // I asked AI to generate more website data for me, I didnt want to but this was fucking obnoixous.

    {
        "title": "Buy the Best SEO Optimization Tool - SearchBoost Pro",
        "url": "#",
        "description": "AD: Get your website to the top of the search rankings! Our proprietary AI tool boosts engagement by 400%. Buy now for 50% off.",
        "sourceType": "commercial",
        "date": "2025-01-15"
    },
    {
        "title": "My Personal Blog: Why I Left Silicon Valley",
        "url": "#",
        "description": "It's been six months since I quit my job at a major tech firm, and I wanted to share some reflections on the industry and the 'search' monopoly.",
        "sourceType": "blog / personal",
        "date": "2024-11-01"
    },
    {
        "title": "A Peer-Reviewed Study on Algorithmic Bias in Search",
        "url": "#",
        "description": "Published in the Journal of Computer Science, this paper analyzes systemic bias in large-scale search engines, focusing on gender and racial representations.",
        "sourceType": "academic",
        "date": "2024-09-30"
    },
    {
        "title": "Reddit - r/webdev: How does Google ranking actually work?",
        "url": "#",
        "description": "Hey everyone, I'm trying to understand why my personal site is getting buried. Does anyone have a good breakdown of the key SEO factors in 2025?",
        "sourceType": "forum / discussion",
        "date": "2025-01-10"
    },
    {
        "title": "Shopify: How to Rank Higher on Google in 2025",
        "url": "#",
        "description": "Learn how to optimize your e-commerce store to show up first in search results. Our guide covers keywords, site speed, and backlink strategies.",
        "sourceType": "commercial",
        "date": "2024-12-18"
    },
    {
        "title": "FTC.gov: A Guide to Online Advertising and Endorsements",
        "url": "#",
        "description": "The official guide from the Federal Trade Commission on how advertisers must disclose sponsored content on the web and social media.",
        "sourceType": "government",
        "date": "2024-03-22"
    },
    {
        "title": "Wikipedia: Search Engine Optimization",
        "url": "#",
        "description": "Search engine optimization (SEO) is the process of improving the quality and quantity of website traffic to a website or a web page from search engines.",
        "sourceType": "wiki",
        "date": "2024-11-05"
    },
    {
        "title": "MIT Technology Review: The Dangers of Black-Box Algorithms",
        "url": "#",
        "description": "When we don't know how an algorithm makes decisions, we can't correct for its errors or biases. A look into the opacity of modern AI.",
        "sourceType": "academic / news",
        "date": "2024-11-30"
    },
    {
        "title": "Top 10 Best SEO Tools (2025 Review)",
        "url": "#",
        "description": "We review the best tools for getting your site ranked. Our number one pick is SearchBoost Pro, which offers unparalleled performance...",
        "sourceType": "commercial / affiliate",
        "date": "2025-01-20"
    },
    {
        "title": "My Boulder Hiking Blog: A Trip to Chautauqua",
        "url": "#",
        "description": "Just got back from an amazing hike in Boulder! The Flatirons were beautiful. Here are some of my unedited photos from the trip.",
        "sourceType": "blog / personal",
        "date": "2024-10-28"
    },
    {
        "title": "Stack Overflow: 'Why is my JavaScript fetch() failing?'",
        "url": "#",
        "description": "I'm trying to call the GNews API from my front-end but I keep getting a CORS error. Is there something wrong with my code?",
        "sourceType": "forum / discussion",
        "date": "2024-11-04"
    },
    {
        "title": "NIST.gov: AI Risk Management Framework",
        "url": "#",
        "description": "The National Institute of Standards and Technology provides a framework for managing risks associated with artificial intelligence.",
        "sourceType": "government",
        "date": "2024-07-19"
    }
]